name: blockspot

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./app:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "127.0.0.1:8053:80/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'lxBfqgC3We9J57'
    volumes:
      - pihole_data:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped

  kiwix:
    container_name: kiwix
    image: ghcr.io/kiwix/kiwix-serve:latest
    ports:
      - "127.0.0.1:1200:8080"
    restart: unless-stopped
    volumes:
      - "C:/blockspot/data/kiwix:/data"
    command: --urlRootLocation=/kiwix *.zim

  mapserver:
    container_name: mapserver
    image: maptiler/tileserver-gl:latest
    ports:
      - "127.0.0.1:1300:8080"
    volumes:
      - "C:/blockspot/data/mapserver:/data"
    command: ["--mbtiles", "osm-2020-02-10-v3.11_north-america_us-northeast.mbtiles", "--public_url", "http://192.168.8.211/mapserver/"]
    restart: unless-stopped

  osrm:
    container_name: osrm
    image: ghcr.io/project-osrm/osrm-backend:latest
    ports:
      - "127.0.0.1:1400:5000"
    volumes:
      - "C:/blockspot/data/osrm:/data"
    command: osrm-routed --algorithm ch /data/us-northeast-latest.osrm
    restart: unless-stopped

  geo-search:
    container_name: geo-search
    image: python:3.12-slim
    ports:
      - "127.0.0.1:1500:5000"
    working_dir: /app
    volumes:
      - "C:/blockspot/data/geo-search:/app"
    command: >
      sh -c "
      pip install fastapi uvicorn sqlite-utils &&
      uvicorn app:app --host 0.0.0.0 --port 5000
      "
    restart: unless-stopped

  geo-import:
    container_name: geo-import
    image: python:3.12-slim

    working_dir: /app

    volumes:
      - "C:/blockspot/data/geo-search:/app"
      - "C:/blockspot/data/osm:/data"

    command: >
      sh -c "
      apt-get update &&
      apt-get install -y libexpat1 &&
      pip install osmium &&
      python import_osm.py
      "

volumes:
  caddy_data:
  caddy_config:
  pihole_data:
  pihole_dnsmasq: