name: blockspot

services:

  kiwix:
    container_name: kiwix
    image: ghcr.io/kiwix/kiwix-serve:latest
    ports:
      - "1200:8080"
    restart: unless-stopped
    volumes:
      - "C:/Server/kiwix/zim:/data"
    command: "*.zim"

  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./app:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  mapserver:
    container_name: mapserver
    image: maptiler/tileserver-gl:latest
    ports:
      - "1300:8080"
    volumes:
      - "C:/server/data/mapserver:/data"
    command: ["--mbtiles", "osm-2020-02-10-v3.11_north-america_us-northeast.mbtiles", "--public_url", "http://192.168.8.211/mapserver/"]
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: